<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '9,14,15,16',
    'catname' => 'Unimation',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'guanyuyi',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_about","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'unimation',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => 'News',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'xinwenzhongxin',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '5',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_news","show_template":"show_news","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'news',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '11,17,18,19',
    'catname' => 'Product',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'chanpinzhongxin',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_product","list_template":"list_product","show_template":"show_product","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'product',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => 'Human Resources',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'rencaizhaopin',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_job","show_template":"show_job","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'human resources',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '13,22,23',
    'catname' => 'Contact Us',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'lianxiwomen',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_contact","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'contact us',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '14',
    'catname' => 'Company introduction',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'guanyuyi/',
    'catdir' => 'gongsijieshao',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=14',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_about_gongsijieshao","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '14',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'company introduction',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '15',
    'catname' => 'Company size',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'guanyuyi/',
    'catdir' => 'gongsiguimo',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=15',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_about_gongsiguimo","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '15',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'company size',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '16',
    'catname' => 'Cooperative partner',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'guanyuyi/',
    'catdir' => 'hezuohuoban',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=16',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_about_hezuohuoban","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '16',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'cooperative partner',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  17 => 
  array (
    'catid' => '17',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '17',
    'catname' => 'automation equipment',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'chanpinzhongxin/',
    'catdir' => 'zidonghuashebei',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=17',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_product","list_template":"list_product","show_template":"show_product","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '17',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'automation equipment',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  18 => 
  array (
    'catid' => '18',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '18',
    'catname' => 'Test equipment',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'chanpinzhongxin/',
    'catdir' => 'ceshishebei',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=18',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_product","list_template":"list_product","show_template":"show_product","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '18',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'test equipment',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  19 => 
  array (
    'catid' => '19',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '3',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '19',
    'catname' => 'Dynamometer equipment',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'chanpinzhongxin/',
    'catdir' => 'cegongshebei',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=19',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category_product","list_template":"list_product","show_template":"show_product","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '19',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'dynamometer equipment',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  22 => 
  array (
    'catid' => '22',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '13',
    'arrparentid' => '0,13',
    'child' => '0',
    'arrchildid' => '22',
    'catname' => 'Contact information',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'lianxiwomen/',
    'catdir' => 'lianxifangshi',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=22',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_contact_lianxifangshi","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '22',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'contact information',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  23 => 
  array (
    'catid' => '23',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '13',
    'arrparentid' => '0,13',
    'child' => '0',
    'arrchildid' => '23',
    'catname' => 'Online Message',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'lianxiwomen/',
    'catdir' => 'zaixianliuyan',
    'url' => 'http://localhost/Unimation/en/index.php?m=content&c=index&a=lists&catid=23',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list_contact_zaixianliuyan","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '23',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'online message',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>